name: myankapi
description: "A onestop service app for Myanmar pepople who lives in Bangkok, Bang kapi"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.1.2
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  mockito: ^5.4.4
  flutter_bloc: ^8.1.6
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10 # dart run build_runner build --delete-conflicting-outputs
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: sfpro
      fonts:
        - asset: assets/fonts/sf_pro_regular.otf
          weight: 400
        - asset: assets/fonts/sf_pro_bold.otf
          weight: 600
